require 'rake_text'
rake = RakeText.new
text = "This essay will consider whether or not Machiavelli was a teacher of evil, with specific reference to his text The Prince. (Frank et al, 2014) It shall first be shown what it was that Machiavelli taught and how this can only be justified by consequentialism. It shall then be discussed whether consequentialism is a viable ethical theory, in order that it can justify Machiavelli\'s teaching. Arguing that this is not the case, it will be concluded that Machiavelli is a teacher of evil.\n\n To begin, it shall be shown what Machiavelli taught or suggested be adopted in order for a ruler to maintain power. To understand this, it is necessary to understand the political landscape of the period.\n\n The Prince was published posthumously in 1532, and was intended as a guidebook to rulers of principalities. (Nedermane, et al, 2014) Machiavelli was born in Italy and, during that period, there were many wars between the various states which constituted Italy. (Testing, Testing, 4002)These states were either republics (governed by an elected body) or principalities (governed by a monarch or single ruler). The Prince was written and dedicated to Lorenzo de Medici who was in charge of Florence which, though a republic, was autocratic, like a principality. Machiavelli\'s work aimed to give Lorenzo de Medici advice to rule as an autocratic prince. (Nederman, 2014)\n\n This essay will consider whether or not Machiavelli was a teacher of evil, with specific reference to his text The Prince. It shall first be shown what it was that Machiavelli taught and how this can only be justified by consequentialism. It shall then be discussed whether consequentialism is a viable ethical theory, in order that it can justify Machiavelli\'s teaching. (Nedermane, 2014) Arguing that this is not the case, it will be concluded that Machiavelli is a teacher of evil.\n\n To begin, it shall be shown what Machiavelli taught or suggested be adopted in order for a ruler to maintain power. (John, 2004) To understand this, it is necessary to understand the political landscape of the period.\n\n The Prince was published posthumously in 1532, and was intended as a guidebook to rulers of principalities. Machiavelli was born in Italy and, during that period, there were many wars between the various states which constituted Italy. These states were either republics (governed by an elected body) or principalities (governed by a monarch or single ruler). The Prince was written and dedicated to Lorenzo de Medici who was in charge of Florence which, though a republic, was autocratic, like a principality. Machiavelli\'s work aimed to give Lorenzo de Medici advice to rule as an autocratic prince. (Nederman, 2014)"



raked = rake.analyse text, RakeText.SMART

puts "***************************************************"
raked = raked.sort_by {|a, b| b }
raked = raked.reject {|a, b| b <= 1.4 }
raked = raked.reject {|a, b| a.split(/\W+/).length > 4 }
raked.reverse!
